assetmanager/urls.py
from django.urls import path, re_path
from . import views 

app_name = 'assetmanager'
urlpatterns = [
    path('', views.assetList.as_view(), name='assetlist'),
    path('create/', views.createAsset, name='create_asset'),
    re_path(r'^update/(?P<id>\d+)/$', views.asset_update, name="update_asset"),
    re_path(r'^delete/(?P<id>\d+)/$', views.asset_delete, name="delete_asset"),
]

django-dynamic-formset-master/demo/urls.py
import django
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^examples/', include('example.urls')),
]

if 'ajax_select' in settings.INSTALLED_APPS:
    # If django-ajax-selects is installed, include its URLs:
    urlpatterns += [
        url(r'^ajax-select/', include('ajax_select.urls'))
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1],
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    ]

lms/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # matches /accounts/****
    path('accounts/', include('accounts.urls')),
    
    # matches /dashboard/****
    path('dashboard/', include('dashboard.urls')),

    # matches /asset/****
    path('asset/', include('assetmanager.urls')),

    # matches /loans/****
    path('loans/', include('loan.urls')),

    # Redirect /user-guide/ to dashboard user-guide view
    path('user-guide/', RedirectView.as_view(url='/dashboard/user-guide/', permanent=False)),
]

assetmanager/models.py
from django.db import models
from dashboard.models import baseModel
from django.contrib.auth.models import User
from dashboard.choices import STATUS_CHOICES


class Asset(baseModel):
    name=models.CharField(max_length=50)
    description=models.TextField()
    expiry_date=models.DateField(null=True)
    inspection_date=models.DateField(null=True)
    owner=models.ForeignKey(User,on_delete=models.CASCADE,)
    status=models.CharField(max_length=20,choices=STATUS_CHOICES, null=True)
    value=models.IntegerField(null=True)

    def __str__(self):
    	return self.name

	

class assetDocument(baseModel):
	upload_date=models.DateField(auto_now_add=True)
	document_name=models.CharField(max_length=200, null=True, blank=True)
	file=models.FileField(upload_to='assetdocuments/')
	proof_of=models.ForeignKey(Asset,on_delete=models.CASCADE)

	def __str__(self):
		return self.document_name
	

assetmanager/forms.py
from django import forms
from .models import Asset, assetDocument
from django.contrib.auth.models import User

class assetForm(forms.ModelForm):
	def __init__(self,request,*args,**kwargs):
		super (assetForm,self ).__init__(*args,**kwargs) # populates the post
		self.fields['owner'].queryset = User.objects.filter(person__company=request.user.person.company).filter(is_staff=False)
		
	class Meta:
		model=Asset
		exclude=['created_by','updated_by','updated_on','company','branch']
		widgets={
	            'name':forms.TextInput(attrs={'class':'form-control lmsinput', 'required':True}),
	            'owner':forms.Select(attrs={'class':'form-control lmsinput', 'required':True}),
	            'description':forms.Textarea(attrs={'class':'form-control lmsinput', 'required':True}),
	            'inspection_date':forms.DateInput(attrs={'class':'form-control lmsinput', 'required':True}),
	            'expiry_date':forms.DateInput(attrs={'class':'form-control lmsinput', 'required':True}),
	            'value':forms.NumberInput(attrs={'class':'form-control lmsinput', 'required':True}),
	            'status':forms.Select(attrs={'class':'form-control lmsinput'}),
	            }

class assetDocumentForm(forms.ModelForm):
	class Meta:
		model=assetDocument
		exclude=['created_by','updated_by','updated_on','company','branch','proof_of']
		widgets={
				'document_name':forms.TextInput(attrs={'class':'form-control ', 'required':True, 'placeholder':'enter document type'}),
				'file':forms.FileInput(attrs={'class':'form-control ', 'required':True}),
		}

assetmanager/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from .models import Asset, assetDocument
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import assetForm,assetDocumentForm
from django.db import transaction
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.forms.models import modelformset_factory
import pdb
# Create your views here.
class assetList(LoginRequiredMixin, ListView):
	login_url = '/account/login/'
	model=Asset
	template_name = 'assetmanager/asset_list.html'
	context_object_name = 'asset_list'
	
	
	def get_queryset(self):
		return Asset.objects.filter(company=self.request.user.person.company)


@login_required(login_url='/account/login/')
@transaction.atomic
def save_asset_form(request, form, template_name,formset):
	data = dict()
	if request.method == 'POST' :
		if form.is_valid() and formset.is_valid():
			asset=form.save(commit=False)
			asset.audit(request)
			asset.save()
			assetDocument.objects.filter(proof_of=asset).delete()
			data['form_is_valid'] = True
			for document_form in formset:
				name=document_form.cleaned_data['document_name']
				file=document_form.cleaned_data['file']
				document=assetDocument.objects.create(proof_of=asset, document_name=name, file=file)
				document.audit(request)
				document.save()
			assets = Asset.objects.all()
			#pdb.set_trace()
			data['html_product_list'] = render_to_string('assetmanager/includes/partial_asset_list.html', {
                'asset_list': assets
            })
		else:
			data['form_is_valid'] = False
	context = {'form': form, 'formset':formset}
	#pdb.set_trace()
	data['html_form'] = render_to_string(template_name, context, request=request)
	#pdb.set_trace()
	return JsonResponse(data)


@login_required(login_url='/account/login/')
@transaction.atomic
def createAsset(request):
	modelformset=modelformset_factory(assetDocument, assetDocumentForm)
	if request.method == 'POST':
		form = assetForm(request,request.POST)
		documentformset=modelformset(data=request.POST, files=request.FILES)
	else:
		form=assetForm(request)
		documentformset=modelformset()
		#pdb.set_trace()
	return save_asset_form(request, form, 'assetmanager/includes/partial_asset_create.html', documentformset)

@login_required(login_url='/account/login/')
@transaction.atomic
def asset_update(request,id):
	modelformset=modelformset_factory(assetDocument,assetDocumentForm,extra=1)
	asset=get_object_or_404(Asset, id=id)
	documentobjects=assetDocument.objects.filter(proof_of=asset)
	documents=[{'name':document.document_name, 'file':document.file} for document in documentobjects]
	#pdb.set_trace()
	if request.method =='POST':
		form=assetForm(request=request,data=request.POST, instance=asset)
		documentformset=modelformset(data=request.POST, files=request.FILES)
	else:
		documentformset=modelformset(initial=documents)
		#pdb.set_trace()
		form=assetForm(request=request,instance=asset)
	return save_asset_form(request, form, 'assetmanager/includes/partial_asset_update.html',documentformset)

@login_required(login_url='/account/login/')
def asset_delete(request,id):
	asset=get_object_or_404(Asset, id=id)
	data = dict()
	#pdb.set_trace()
	if request.method=='POST':
		assetDocument.objects.filter(proof_of=asset).delete()
		asset.delete()
		data['form_is_valid'] = True  # This is just to play along with the existing code
		assets = Asset.objects.all()
		data['html_product_list'] = render_to_string('assetmanager/includes/partial_asset_list.html', {
		    'asset_list': assets
		})
	else:
		context = {'asset': asset}
		data['html_form'] = render_to_string('assetmanager/includes/partial_asset_delete.html',
		context,
		request=request,
		)
	return JsonResponse(data)
	





	
		





	

assetmanager/templates/assetmanager/includes/partial_asset_create.html
<form method="post" class="js-product-create-form" enctype="multipart/form-data" action="{% url 'assetmanager:create_asset' %}">
{%csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modla-title mtitle">Create New Asset</h4>
		{% include 'assetmanager/includes/partial_asset_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Create</button>

</form>

assetmanager/templates/assetmanager/includes/partial_asset_delete.html
<form method="post" action="{% url 'assetmanager:delete_asset' asset.id %}" class="js-product-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title mtitle">Confirm Asset delete</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the Asset <strong>{{ asset.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Asset</button>
  </div>
</form>

assetmanager/templates/assetmanager/includes/partial_asset_form.html
{%for field in form %}
			<div class="form-group">
				{{field.label_tag}}
				{{field}}
				{% for error in field.errors %}
				<p class="error">{{error}}</p>
				{%endfor%}
			</div>
		{%endfor%}
<hr>
{{ formset.management_form }}

{%for documentform in formset %}

<div class="form-container form-inline  formset">
	{% for field in documentform %}
		     <div class="form-group  ">
				{{field}}
				{% for error in field.errors %}
				<p class="error">{{error}}</p>
				{%endfor%}
			</div>
	{%endfor%}
</div>
{% endfor %}
<button type="button" class="btn js-add-formset formset"  id="add_more">Add more</button>
<button type="button" class="btn js-remove-formset formset">Remove last</button>

assetmanager/templates/assetmanager/includes/partial_asset_list.html
													{% for asset in asset_list %}
			                                        <tr>
			                                            <th scope="row">{{asset.pk}}</th>
			                                            <td>{{asset.name}}</td>
			                                            <td>{{asset.expiry_date}}</td>
			                                            <td>{{asset.inspection_date}} </td>
			                                            <td>{{asset.owner}}</td>
			                                            <td>{{asset.status}}</td>
			                                            <td>
				                                            
					                                            <button type="button"
														              class="btn btn-success btn-sm js-update-product"
														              data-url="{% url 'assetmanager:update_asset' asset.pk %}">
														                <span class="glyphicon glyphicon-pencil"></span> Edit
														        </button>
														        <button type="button"
														              class="btn btn-warning btn-sm js-delete-product"
														              data-url="{% url 'assetmanager:delete_asset' asset.pk %}">
														                <span class="glyphicon glyphicon-pencil"></span> Delete
														        </button-->

														   
													    </td>
													</tr>
			                                       {% empty %}
			                                       <tr>
				                                       <td colspan="7" class="text-center">No Asset Found</td>
			                                       </tr>
			                                       {% endfor %}
			                                       

assetmanager/templates/assetmanager/includes/partial_asset_update.html
<form method="post" class="js-product-update-form" action="{% url 'assetmanager:update_asset'   form.instance.id %}">
{%csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modla-title mtitle">Update Asset</h4>
		{% include 'assetmanager/includes/partial_asset_form.html ' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Update</button>

</form>