accounts/urls.py
from django.urls import path, re_path
from . import views
from .views import clientList

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('borrower/', clientList.as_view(), name="clientlist"),
    re_path(r'^borrower/update/(?P<id>\d+)/$', views.clientUpdate, name='update_client'),
    path('borrower/create/', views.createCLient, name='create_client'),
    re_path(r'^borrower/delete/(?P<id>\d+)/$', views.clientDelete, name='delete_client'),
]

django-dynamic-formset-master/demo/urls.py
import django
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^examples/', include('example.urls')),
]

if 'ajax_select' in settings.INSTALLED_APPS:
    # If django-ajax-selects is installed, include its URLs:
    urlpatterns += [
        url(r'^ajax-select/', include('ajax_select.urls'))
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1],
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    ]

lms/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # matches /accounts/****
    path('accounts/', include('accounts.urls')),
    
    # matches /dashboard/****
    path('dashboard/', include('dashboard.urls')),

    # matches /asset/****
    path('asset/', include('assetmanager.urls')),

    # matches /loans/****
    path('loans/', include('loan.urls')),

    # Redirect /user-guide/ to dashboard user-guide view
    path('user-guide/', RedirectView.as_view(url='/dashboard/user-guide/', permanent=False)),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from dashboard.models import baseModel
from dashboard.choices import *
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class person(baseModel):
	user=models.OneToOneField(User,on_delete=models.CASCADE,related_name='person', default='1')
	title=models.CharField(max_length=200, blank=True,choices=TITLE_CHOICES)
	fullname=models.CharField(max_length=200, blank=True)
	full_address=models.CharField(max_length=200, blank=True)
	city=models.CharField(max_length=200, blank=True)
	zip=models.CharField(max_length=200, blank=True)
	state=models.CharField(max_length=200, blank=True)
	phone=models.CharField(max_length=200, blank=True)
	gender=models.CharField(max_length=200, choices=GENDER_CHOICES, blank=True)
	dob=models.DateField( blank=True, null=True)
	state_of_origin=models.CharField(max_length=200, blank=True)
	current_salary=models.CharField(max_length=200, blank=True)
	employment_date=models.DateField(blank=True, null=True)
	lga=models.CharField(max_length=200, blank=True)
	job_description=models.TextField( blank=True)
	marital_status=models.CharField(max_length=200, choices=RELATIONSHIP_STATUS_CHOICES, blank=True)
	picture=models.ImageField(max_length=200, blank=True,upload_to='employee/')
	bio=models.TextField(max_length=200, blank=True)




class Client(person):
	current_employer=models.CharField(max_length=200, blank=True)
	years_in_workplace=models.TextField(max_length=100, blank=True)
	vehicles_owned=models.CharField(max_length=200, blank=True)
	years_at_residence=models.CharField(max_length=200, blank=True)
	loan_officer=models.ForeignKey(User,on_delete=models.CASCADE, help_text='Someone who manages the client among your staffs',related_name='officer',null=True, blank=True)
	residential_status=models.CharField(max_length=200, choices=RESIDENTIAL_STATUS_CHOICES, blank=True)
	educational_status=models.CharField(max_length=200,choices=EDUCATIONAL_STATUS_CHOICES, blank=True)
    
class Employee(person):
	years_in_workplace=models.TextField(max_length=100, blank=True)
	manager=models.ForeignKey(User,on_delete=models.CASCADE,related_name='manager', blank=True, null=True)
	educational_status=models.CharField(max_length=200,choices=EDUCATIONAL_STATUS_CHOICES, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender,instance,created, **kwargs):
    if created:
        if instance.is_staff==True:
            Employee.objects.create(user=instance)
        else:
            Client.objects.create(user=instance)
'''
@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if instance.is_staff==True:
        instance.employee.save()
    else:
        instance.client.save()
'''




	

accounts/forms.py
from django import forms
from .models import Client
from django.contrib.auth.models import User

class LoginForm(forms.Form):
	username=forms.CharField(label='Username',
	help_text='Please enter you username', 
	widget=forms.TextInput(attrs={'class':'form-control lmsinput', 'required': True}))
	
	password=forms.CharField(label='Password',
	help_text='Please Enter Your Password',
	widget=forms.PasswordInput(attrs={'class':'form-control lmsinput', 'required':True}))


class clientForm(forms.ModelForm):
	class Meta:
		model=Client
		exclude=['user','created_by','updated_by','updated_on','company','branch']
		widgets = {
            'title': forms.Select(attrs={'class': 'form-control', 'value':'Mr', 'required':True}),
            'fullname':forms.TextInput(attrs={'class': 'form-control','value':'Mr',  'required':True}),
            'full_address':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'city':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'zip':forms.TextInput(attrs={'class': 'form-control', 'value':'Mr','required':True}),
            'state':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'phone':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'state_of_origin':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'lga':forms.TextInput(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'loan_officer':forms.Select(attrs={'class': 'form-control','value':'Mr', 'required':True}),
            'gender':forms.Select(attrs={'class': 'form-control', 'required':True}),
            'dob':forms.DateInput(attrs={'class':'form-control', 'value':'1/1/1994','required':True}),
            'marital_status':forms.Select(attrs={'class':'form-control', 'required':True}),
            'picture':forms.FileInput(attrs={'class':'form-control'}),
            'bio':forms.Textarea(attrs={'class':'form-control', 'value':'Mr'}),
            'current_employer':forms.TextInput(attrs={'class':'form-control','value':'Mr', 'required':True}),
            'current_salary':forms.TextInput(attrs={'class':'form-control', 'value':'Mr','required':True}),
            'job_description':forms.TextInput(attrs={'class':'form-control','value':'Mr', 'required':True}),
            'years_in_workplace':forms.TextInput(attrs={'class':'form-control','value':'Mr', 'required':True}),
            'state_of_origin':forms.TextInput(attrs={'class':'form-control', 'value':'Mr','required':True}),
            'vehicles_owned':forms.TextInput(attrs={'class':'form-control','value':'Mr', 'required':True}),
            'years_at_residence':forms.TextInput(attrs={'class':'form-control', 'value':'Mr','required':True}),
            'residential_status':forms.Select(attrs={'class':'form-control', 'value':'Mr','required':True}),
            'educational_status':forms.Select(attrs={'class':'form-control', 'value':'Mr','required':True}),
            'employment_date':forms.DateInput(attrs={'class':'form-control', 'value':'Mr'}),
            }

class userForm(forms.ModelForm):
	class Meta:
		model=User
		fields=('first_name', 'last_name','email','username','password')
		widgets={'password':forms.PasswordInput(attrs={'class': 'form-control', 'required':True, 'value':''}),
		'username':forms.TextInput(attrs={'class':'form-control', 'required':True, 'value':''}),
		'first_name':forms.TextInput(attrs={'class':'form-control', 'required':True, 'value':''}),
		'last_name':forms.TextInput(attrs={'class':'form-control', 'required':True, 'value':''}),
		'email':forms.EmailInput(attrs={'class':'form-control', 'required':True, }),
		 }	 

accounts/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.template.loader import render_to_string
from django.contrib.auth import (authenticate,login as auth_login, logout as auth_logout)
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from .forms import LoginForm
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.views.generic.list import ListView
from django.contrib.auth.models import User
from .forms import clientForm,userForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.hashers import make_password
from .models import Client
from django.db.models import Q
import pdb

def login(request):
	message=''
	if request.user.is_authenticated:
		
		return HttpResponseRedirect(reverse('dashboard:home', current_app='dashboard'))
	if request.method == "POST":
		form=LoginForm(request.POST)
		if form.is_valid():
			_username=form.cleaned_data['username']
			_password=form.cleaned_data['password']
			user=authenticate(username=_username, password=_password)
			if user is not None:
				if user.is_active:
					auth_login(request, user)
					if request.GET.get('next'):
						return redirect(request.GET.get('next'))
					else:
					    return HttpResponseRedirect(reverse('dashboard:home', current_app='dashboard'))
				else:
					message = 'Your account is not activated'
			else:
				message = 'Invalid login, please try again.'
	form=LoginForm()			
	context = {'message': message, 'form':form}


	return render(request, 'accounts/login.html', context)

def logout(request):
	if request.user.is_authenticated():
		auth_logout(request)
		return HttpResponseRedirect(reverse('accounts:login', current_app='accounts'))
	else:
		return HttpResponseRedirect(reverse('accounts:login', current_app='accounts'))




class clientList(LoginRequiredMixin,ListView):
	login_url = '/account/login/'
	model=User
	template_name = "accounts/client_list.html"

	def get_context_data(self, **kwargs):
		context = super(clientList, self).get_context_data(**kwargs)
		context['graphs']='testing'
		context['client_list']=User.objects.filter(Q(is_staff=False), person__company= self.request.user.person.company)
		return context

@login_required(login_url='/account/login/')
#@transaction.atomic
def createCLient(request):
	if request.method=='POST':
		clientform=clientForm(request.POST)
		userform=userForm(request.POST)
	else:
		clientform=clientForm()
		userform=userForm()
	return save_client_form(request,userform,'accounts/includes/partial_client_create.html',clientform,)

def clientUpdate(request, id):
	data=dict()
	user=get_object_or_404(User, id=id)
	client=get_object_or_404(Client, user=user)
	data['form_is_valid']=True
	if request.method == 'POST':
		clientform = clientForm(data=request.POST, instance=client)
		userform=userForm(data=request.POST, instance=client)
		if clientform.is_valid() and userform.is_valid():
			userform.save()
			client=clientform.save(commit=False)
			client.audit(request)
			client.save()
			borrowers=User.objects.filter(Q(is_staff=False), person__company= request.user.person.company)
			data['html_product_list']=render_to_string('accounts/includes/partial_client_list.html', {
	               'client_list': borrowers
	            })
		else:
			data['form_is_valid']=False
		context = {'userform': userform, 'clientform':clientform}
		data['html_form'] = render_to_string('accounts/includes/partial_client_update.html', context, request=request)
		return JsonResponse(data)
	else:
		clientform=clientForm(instance=client)
		userform=userForm(instance=user)
		return save_client_form(request, userform, 'accounts/includes/partial_client_update.html', clientform)

def clientDelete(request,id):
	data=dict()
	user=get_object_or_404(User, id=id)
	data['form_is_valid']=True
	if request.method=='POST':
		user.delete()
		data['form_is_valid'] = True  # This is just to play along with the existing code
		borrowers=User.objects.filter(Q(is_staff=False), person__company= request.user.person.company)
		data['html_product_list'] = render_to_string('accounts/includes/partial_client_list.html', {
           'client_list': borrowers
        })
	else:
		context = {'client': user}
		data['html_form'] = render_to_string('accounts/includes/partial_client_delete.html',
		context,
		request=request,
		)
	return JsonResponse(data)
		

@login_required(login_url='/account/login/')
@transaction.atomic
def save_client_form(request, userform, template_name,clientform):
	data = dict()
	if request.method=='POST':
		if clientform.is_valid() and userform.is_valid():
			data['form_is_valid'] = True
			password=request.POST.get('password')
			hashpassword=make_password(password)
			try:
				new_user=User.objects.create(
					first_name=request.POST.get('first_name'), 
					is_staff=False, 
					last_name=request.POST.get('last_name'),
					username=request.POST.get('username'),
					password=hashpassword,
					email=request.POST.get('email'),
					)
				new_user.save()
				try:
				    profile=Client.objects.get(user=new_user)
				except :
					profile=Client.objects.create(user=new_user)
				clientform=clientForm(request.POST, instance=profile)
				client=clientform.save(commit=False)
				client.audit(request)
				client.save()
				borrowers=User.objects.filter(Q(is_staff=False), person__company= request.user.person.company)
				data['html_product_list'] = render_to_string('accounts/includes/partial_client_list.html', {
	               'client_list': borrowers
	            })
				#pdb.set_trace()
			except:
				#pdb.set_trace()
				#userform.errors='Username already exist. Please try another one'
				pdb.set_trace()
				data['form_is_valid']=False	
		else:
			data['form_is_valid'] = False	
	#pdb.set_trace()
	context = {'userform': userform, 'clientform':clientform}
	data['html_form'] = render_to_string(template_name, context, request=request)
	
	return JsonResponse(data)


		
	
	    

accounts/templates/accounts/includes/partial_client_create.html
<form method="post" class="js-product-create-form" enctype="multipart/form-data" action="{% url 'accounts:create_client' %}">
{%csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modla-title mtitle">Create New Asset</h4>
		{% include 'accounts/includes/partial_client_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Create</button>

</form>

accounts/templates/accounts/includes/partial_client_delete.html
<form method="post" action="{% url 'accounts:delete_client' client.id %}" class="js-product-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title mtitle">Confirm Client delete</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the Client <strong>{{ client.first_name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Client</button>
  </div>
</form>

accounts/templates/accounts/includes/partial_client_form.html
{%for field in userform %}
			<div class="form-group">
				{{field.label_tag}}
				{{field}}
				{% for error in field.errors %}
				<p class="error">{{error}}</p>
				{%endfor%}
			</div>
		{%endfor%}
<hr>
	{% for field in clientform %}
		     <div class="form-group  ">
			    {{field.label_tag}}
				{{field}}
				{% for error in field.errors %}
				<p class="error">{{error}}</p>
				{%endfor%}
			</div>
	{%endfor%}

accounts/templates/accounts/includes/partial_client_list.html
							{% for client in client_list %}
			                                        <tr>
			                                            <th scope="row">{{client.pk}}</th>
			                                            <td>{{client.person.title}}</td>
			                                            <td>{{client.first_name}}</td>
			                                            <td>{{client.person.phone}} </td>
			                                            <td>{{client.email}}</td>
			                                            <!--td>{{asset.status}}</td-->
			                                            <td>
				                                            
					                                            <button type="button"
														              class="btn btn-success btn-sm js-update-product"
														              data-url="{% url 'accounts:update_client' client.id %}">
														                <span class="glyphicon glyphicon-pencil"></span> Edit
														        </button>
														        <button type="button"
														              class="btn btn-warning btn-sm js-delete-product"
														              data-url="{% url 'accounts:delete_client' client.id %}">
														                <span class="glyphicon glyphicon-pencil"></span> Delete
														        </button-->

														   
													    </td>
													</tr>
			                                       {% empty %}
			                                       <tr>
				                                       <td colspan="7" class="text-center">No Borrower Found. Please Create</td>
			                                       </tr>
			                                       {% endfor %}
			                                       

accounts/templates/accounts/includes/partial_client_update.html
<form method="post" class="js-product-update-form" action="{% url 'accounts:update_client'   userform.instance.id %}">
{%csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modla-title mtitle">Update Asset</h4>
		{% include 'accounts/includes/partial_client_form.html ' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Update</button>

</form>