dashboard/urls.py
from django.urls import path, re_path
from . import views 
from .views import HomeView

app_name = 'dashboard'
urlpatterns = [
    # /dashboard/
    path('', HomeView.as_view(), name='home'),
    path('loan_type/', views.loantype, name='loanType'),
    path('product/create/', views.product_create, name='create_product'),
    re_path(r'^product/update/(?P<id>\d+)/$', views.product_update, name="update_product"),
    re_path(r'^product/delete/(?P<id>\d+)/$', views.product_delete, name="delete_product"),
    path('user-guide/', views.user_guide, name='user_guide'),
]

django-dynamic-formset-master/demo/urls.py
import django
from django.conf import settings
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf.urls import url, include

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^examples/', include('example.urls')),
]

if 'ajax_select' in settings.INSTALLED_APPS:
    # If django-ajax-selects is installed, include its URLs:
    urlpatterns += [
        url(r'^ajax-select/', include('ajax_select.urls'))
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1],
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
    ]

lms/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    
    # matches /accounts/****
    path('accounts/', include('accounts.urls')),
    
    # matches /dashboard/****
    path('dashboard/', include('dashboard.urls')),

    # matches /asset/****
    path('asset/', include('assetmanager.urls')),

    # matches /loans/****
    path('loans/', include('loan.urls')),

    # Redirect /user-guide/ to dashboard user-guide view
    path('user-guide/', RedirectView.as_view(url='/dashboard/user-guide/', permanent=False)),
]

dashboard/models.py
from django.contrib.auth.models import User
from django.db import models
from .choices import *
class Company(models.Model):
    name=models.CharField(max_length=200)
    domain=models.CharField(max_length=200)
    primary_color=models.CharField(max_length=200, choices=COLOR_CHOICES)
    website=models.URLField(max_length=500)
    email=models.EmailField()
    owner=models.CharField(max_length=200)
    currency_type=models.CharField(max_length=10, default='NGN', choices=CURRENCY_CHOICES)
    logo=models.ImageField(max_length=200, help_text='require a 100 by 100 img size', upload_to='logos/')
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField( auto_now=True)
    updated_by=models.ForeignKey(User,on_delete=models.CASCADE, blank=True, related_name='created_by_company')
    
class Branch(models.Model):
    full_address=models.CharField(max_length=200)
    city=models.CharField(max_length=200)
    zip=models.CharField(max_length=200)
    state=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    email=models.EmailField()
    company=models.ForeignKey(Company, on_delete=models.CASCADE)
    manager=models.ForeignKey(User,on_delete=models.CASCADE, blank=True,related_name='branch_manager')
    created_by=models.ForeignKey(User,on_delete=models.CASCADE, blank=True,related_name='created_by_on_branch')
    created_on=models.DateTimeField(auto_now_add=True)
    updated_on=models.DateTimeField(auto_now=True)
    updated_by=models.ForeignKey(User,on_delete=models.CASCADE, blank=True,related_name='updated_by_branch')
class baseModel(models.Model):
    created_by=models.ForeignKey(User,on_delete=models.CASCADE,related_name='applicationcreator', blank=True, null=True)
    created_on=models.DateTimeField(auto_now_add=True, blank=True)
    updated_on=models.DateTimeField(auto_now=True, blank=True)
    updated_by=models.ForeignKey(User,on_delete=models.CASCADE, blank=True,related_name='applicationupdater', null=True)
    company=models.ForeignKey(Company,on_delete=models.CASCADE, related_name='applicationcompany',null=True)
    branch=models.ForeignKey(Branch, on_delete=models.CASCADE,related_name='applicationbranch',null=True)

    def audit(self,request):
        self.created_by=request.user
        self.company=request.user.person.company
        self.branch=request.user.person.branch
    

class Bank(baseModel):
    bank_name=models.CharField(max_length=50)
    account_number=models.CharField(max_length=50, null=True)
    account_type=models.CharField(max_length=50, choices=ACCOUNT_CHOICES)
class companyAccount(Bank):
    owner=models.ForeignKey(Company,on_delete=models.CASCADE, related_name="company_account")
    description=models.TextField()
class personAccount(Bank):
    owner=models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_bank')
class documentType(baseModel):
    name=models.CharField(max_length=50)
    description=models.TextField()
    def __str__(self):
        return self.name
    
    
class loanType(baseModel):
    name=models.CharField(max_length=50)
    rate=models.DecimalField(max_digits=5, decimal_places=2)
    description=models.TextField()
    need_collateral=models.BooleanField(help_text='does this type of Loan need Coollateral')
    need_guarantor=models.BooleanField(help_text='does this type of loan need a gurantor')
    market=models.CharField(null=True, help_text="these include the category of people who will be interested in this particular product", max_length=50, choices=MARKET_CHOICES )
    documents=models.ManyToManyField(documentType,help_text="Include documents that are needed here for this particular loan.. You can go to the document section to add or delete document")
    min_amount_allowed=models.IntegerField(null=True, blank=True)#null means that any price
    max_amount_allowed=models.IntegerField(null=True, blank=True)#min price must not be more than maximum price
    interest_type=models.CharField(max_length=50, choices=INTEREST_TYPE_CHOICES, default='Flat Rate')
#class Loan(baseModel):
##  status=models.CharField(max_length=200, choices=STATUS_CHOICES)
# application_date=models.DateField(auto_now_add=True)
    #amount=models.IntegerField()
    #preferred_payment_date=models.DateField()
# method_of_payt=models.CharField(max_length=20,choices=PAYMENT_METHOD )
# bank_account=models.ForeignKey(personAccount, null=True, related_name='loan_payment_account')
# collateral=models.ForeignKey(Asset, related_name='loan_colateral')
# loan_type=models.ForeignKey(loanType)
# issue_date=models.DateField(null=True)
class activityLog(baseModel):
    date=models.DateTimeField(auto_now_add=True)
    initiator=models.ForeignKey(User,on_delete=models.CASCADE)
    description=models.CharField(max_length=200)
    level=models.IntegerField()
class Documents(baseModel):
    upload_date=models.DateField(auto_now_add=True)
    document_type=models.CharField(max_length=200)
    file=models.FileField(upload_to='documents/')
class Message(baseModel):
    subject=models.CharField(max_length=200)
    messages=models.TextField()
    sent_on=models.DateField(auto_now_add=True)
    status=models.CharField(max_length=20, choices=MESSAGE_STATUS)
    sent_by=models.ForeignKey(User,on_delete=models.CASCADE, related_name='message_sender')
    sent_to=models.ForeignKey(User,on_delete=models.CASCADE)









    

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *


class productForm(forms.ModelForm):
      class Meta:
            model=loanType
            exclude=['created_by','updated_by','updated_on','company','branch']
            widgets={
            'name':forms.TextInput(attrs={'class':'form-control lmsinput', 'required':True}),
            'rate':forms.NumberInput(attrs={'class':'form-control lmsinput', 'required':True, 'max':'100', 'min':'0', 'step':'0.1'}),
            'description':forms.Textarea(attrs={'class':'form-control lmsinput', 'required':True}),
            'payment_frequency':forms.Select(attrs={'class':'form-control lmsinput', 'required':True}),
            'tenure':forms.NumberInput(attrs={'class':'form-control lmsinput', 'required':True}),
            'market':forms.Select(attrs={'class':'form-control lmsinput'}),
            }

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db import transaction
from .forms import *#employeeForm, clientForm, userForm
from django.contrib import messages
from django.views.generic import TemplateView
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth.hashers import make_password
from django.http import JsonResponse
from django.template.loader import render_to_string
import pdb
# Create your views here.
#@login_required(login_url='/account/login/')

class HomeView(LoginRequiredMixin,TemplateView):
	login_url = '/account/login/'
	redirect_field_name = 'redirect_to'
	template_name = "dashboard/index.html"


@login_required(login_url='/account/login/')
@transaction.atomic
def loantype(request):
	if request.user.is_staff:
		
		loantype=loanType.objects.filter(company=request.user.person.company)

	else:
		loantype=loanType.objects.filter(company=request.user.client.company)
	return render(request, 'dashboard/loantype.html', {'loantype':loantype})

@login_required(login_url='/account/login/')
def user_guide(request):
	return render(request, 'dashboard/user_guide.html')

@login_required(login_url='/account/login/')
@transaction.atomic
def save_product_form(request, form, template_name):
	data = dict()
	if request.method == 'POST':
		if form.is_valid():
			product=form.save(commit=False)
			product.audit(request)
			product.save()
			data['form_is_valid'] = True
			#pdb.set_trace()
			products = loanType.objects.all()
			data['html_product_list'] = render_to_string('dashboard/includes/partial_product_list.html', {
                'loantype': products
            })
		else:
			data['form_is_valid'] = False
	context = {'form': form}
	data['html_form'] = render_to_string(template_name, context, request=request)
	#pdb.set_trace()
	return JsonResponse(data)

@login_required(login_url='/account/login/')
@transaction.atomic
def product_create(request):
	if request.method == 'POST':
		form = productForm(request.POST)
	else:
		form = productForm()
	return save_product_form(request, form, 'dashboard/includes/partial_product_create.html')

@login_required(login_url='/account/login/')
@transaction.atomic
def product_update(request,id):
	product=get_object_or_404(loanType, id=id)
	if request.method =='POST':
		form=productForm(request.POST, instance=product)
	else:
		form=productForm(instance=product)
	return save_product_form(request, form, 'dashboard/includes/partial_product_update.html')

@login_required(login_url='/account/login/')
def product_delete(request,id):
	product=get_object_or_404(loanType, id=id)
	data = dict()
	#pdb.set_trace()
	if request.method=='POST':
		product.delete()
		data['form_is_valid'] = True  # This is just to play along with the existing code
		products = loanType.objects.all()
		data['html_product_list'] = render_to_string('dashboard/includes/partial_product_list.html', {
		    'loantype': products
		})
	else:
		context = {'product': product}
		data['html_form'] = render_to_string('dashboard/includes/partial_product_delete.html',
		context,
		request=request,
		)
	return JsonResponse(data)

dashboard/templates/dashboard/includes/partial_product_create.html
<form method="post" class="js-product-create-form" action="{% url 'dashboard:create_product' %}">
{%csrf_token %}
	<div class="modal-header mtitle">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modla-title">Create New Product</h4>
		{% include 'dashboard/includes/partial_product_form.html' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Create</button>

</form>

dashboard/templates/dashboard/includes/partial_product_delete.html
<form method="post" action="{% url 'dashboard:delete_product' product.id %}" class="js-product-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title mtitle">Confirm product deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the Product <strong>{{ product.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete Product</button>
  </div>
</form>

dashboard/templates/dashboard/includes/partial_product_form.html
{%for field in form %}
			<div class="form-group">
				{{field.label_tag}}
				{{field}}
				{% for error in field.errors %}
				<p class="error">{{error}}</p>
				{%endfor%}
			</div>
		{%endfor%}

dashboard/templates/dashboard/includes/partial_product_list.html
													{% for product in loantype %}
			                                        <tr>
			                                            <th scope="row">{{product.pk}}</th>
			                                            <td>{{product.name}}</td>
			                                            <td>{{product.rate}}%</td>
			                                            <td>{{product.tenure}} months</td>
			                                            <td>{{product.payment_frequency}}</td>
			                                            <td>{{product.need_guarantor}}</td>
			                                            <td>{{product.need_collateral}}</td>
			                                            <td>
				                                            
					                                            <button type="button"
														              class="btn btn-success btn-sm js-update-product"
														              data-url="{% url 'dashboard:update_product' product.pk %}">
														                <span class="glyphicon glyphicon-pencil"></span> Edit
														        </button>
														        <button type="button"
														              class="btn btn-warning btn-sm js-delete-product"
														              data-url="{% url 'dashboard:delete_product' product.pk %}">
														                <span class="glyphicon glyphicon-pencil"></span> Delete
														        </button>

														   
													    </td>
													</tr>
			                                       {% empty %}
			                                       <tr>
				                                       <td colspan="7" class="text-center">No Porducts Found</td>
			                                       </tr>
			                                       {% endfor %}

dashboard/templates/dashboard/includes/partial_product_update.html
<form method="post" class="js-product-update-form" action="{% url 'dashboard:update_product'  form.instance.id %}">
{%csrf_token %}
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal"  aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<h4 class="modal-title mtitle">Update Product</h4>
		{% include 'dashboard/includes/partial_product_form.html ' %}
	<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	<button class="btn btn-primary" type="submit">Update</button>

</form>